changelog:
  # 除外するラベル
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 新機能 🎉
      labels:
        - enhancement
    - title: 🛠️ 改善 🛠️
      labels:
        - improve
    - title: 🐛 修正 🐛
      labels:
        - bug
    - title: ドキュメント更新 📄
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
